### PR TITLE
add geom_taxalink2 to support data.frame and mapping as input

### PR DESCRIPTION
**Pull request by xiangpin**
`geom_taxalink2` is the updated verison of `geom_taxalink`. It support data.frame as input, the `colour`, `size`, `linetype` and `alpha` can be mapped. When the `data` was provided, the `mapping` should be also provided, which `taxa1` and `taxa2` should be mapped created by `aes`, `aes_` or `aes_string`. In addition, the `hratio`, control the height of curve line, when tree layout is `cirular`, default is 1. `ncp`, the number of control points used to draw the curve, more control points creates a smoother curve, default is 1. They also can be mapped to a column of data.

```
library(treeio)
library(ggplot2)
library(ggtree)

nwk <- system.file("extdata", "sample.nwk", package="treeio")
tree <- read.tree(nwk)
dat <- data.frame(from=c("A", "F", "L"), to=c("E", "K", "M"), h=c(1, 1, 0.1), type=c("t1", "t2", "t3"), s=c(2, 1, 2))
p2 <- ggtree(tree, layout="inward_circular", xlim=c(150, 0)) +
          geom_taxalink2(data=dat, 
                         mapping=aes(taxa1=from, 
                                     taxa2=to, 
                                     color=type, 
                                     size=s), 
                         ncp=10,
                         
offset=0.15) + 
          geom_tiplab(hjust=1) +
          scale_size_continuous(range=c(1,3))
p2
```

taxa_link2

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
I think a better solution is to support both API in one layout, the `geom_taxalink`.

similar to most layers in ggplot2, such as:

```
ggplot(data.frame(x=0:1, y=0:1), aes(x, y)) + geom_blank() + geom_text(x=.5, y=.5, label="hello")
```

**Comment by xiangpin** [comment]
Yes, `geom_taxalink2` also support the function of `geom_taxalink`.

```
library(treeio)
library(ggtree)
library(ggplot2)

p1 <- ggtree(tree, layout="circular") +
      geom_taxalink2(taxa1='A', taxa2='E', color="grey", alpha=0.5, offset=0.05,
                    arrow=grid::arrow(length=grid::unit(0.01, "npc"))) +
      geom_taxalink2(taxa1='F', taxa2='K', color='red', linetype = 'dashed', alpha=0.5, offset=0.05,
                    arrow=grid::arrow(length=grid::unit(0.01, "npc"))) +
      geom_taxalink2(taxa1="L", taxa2="M", color="blue", alpha=0.5, offset=0.05,
                    hratio=0.8, arrow=grid::arrow(length=grid::unit(0.01, "npc"))) +
      geom_tiplab()
```

taxa_link

**Comment by GuangchuangYu** [comment]
I think you can extend `geom_hilight` and `geom_cladelabel` to support aesthetic mapping too.

**Comment by xiangpin** [comment]
Yes, they are similar, I will extend the methods as soon as possible.

**Pull request merged**
