### PR TITLE
Added ggdensitree method

### PR DESCRIPTION
**Pull request by brj1**
I'm finally ready for a PR. I also merged all my commits into a single commit since the history was messy.

ggdensitree can plot lists of phylogenetic trees (or list of treedata) such that
  - tips are aligned in the y axis
  - tips can optionally (actually default) be aligned in the x axis
  - colouring of edges can be match to an aesthetic/scale

Node and tip labeling can only be done on the first tree in the list. It is slow with a large number of trees (> 100)

### CODE REVIEW

**Comment by brj1** [comment]
Do you think that it would be better to add this functionality to multiPhylo plotting?

**Comment by GuangchuangYu** [comment]
I think it should works for multiPhylo.

**Comment by GuangchuangYu** [comment]
I have made [some small modifications](https://github.com/YuLab-SMU/ggtree/commit/87cb27be4e914ab686ec1f34398e9e6b559f4768), mostly for satisfying R check.

And introduce the `branch.length = "none"` parameter to plot the tree using cladogram by default. Otherwise, it may generate very weird figure using example tree like:

```
set.seed(2019)
x = ape::rmtree(3, 10)
```

**Comment by GuangchuangYu** [comment]
thanks for the PR.

**Comment by brj1** [comment]
> And introduce the `branch.length = "none"` parameter to plot the tree using cladogram by default. Otherwise, it may generate very weird figure using example tree like:

Setting `branch.length = "none"` as default may confuse people because the intended purpose of ggdensitree is to plot time scaled trees from beast. In this the tips will be aligned in the x-axis and the figures should not look weird. I can include a better example if you want.

**Pull request merged**
